function ...
    [result...
    ] = ...
LSystemRun( ...
    fileName, ...
    stepsCount)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

lSystem = xml_load(fileName);
result = LSystemRewriteN(lSystem.axiom, lSystem.rules, stepsCount);

return
end
