function ...
    [ architectureOut,  ...
      dataOut...
    ] = ...
AddBiases( ...
    architecture, ...
    data, ...
    biasRanges)
% Expands current architecture by adding biases.
% biasRanges :
%     vector<bool> indexes
%     vector<double> low  
%     vector<double> up 
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
    
    architectureOut = AddBiasConnections(architecture, biasRanges);
    dataOut = AddBiasInputs(data, biasRanges);

return
end
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%

