function ...
    [ result ...
    ] = ...
GetAdjacentVertexes(...
    candidateList, ...
    architecture);
%%%%%%%%%%%%%%%%%%%%%%
    result = [];
    candidatesCount = size(candidateList, 2);

    for index = 1 : candidatesCount
        itemAdjacent = GetAdjacentVertexesSingle(...
                          candidateList(index), ...
                          architecture);
                      
        result = [result itemAdjacent];
    end

    result = unique(result);
return
end
