function ...
    [vertexesToUpdate, ...
    signalOut] = ...
GetStableVertexes(...
    updatedList, ...
    candidateList, ...
    architecture, ...
    weights, ...
    signal)
% updates the signal 
% gets the vertexes list, dependent on the updatedList and 

    vertexesToUpdate = [];
    signalOut = signal;
    candidatesCount = size(candidateList, 2);
    
    for index = 1 : candidatesCount
        candidate = candidateList(index);
        candidateDependencies = GetVertexDependencies( ...
                                    candidate, ...
                                    architecture);
                                
        if ( IsSubset(candidateDependencies, updatedList) )
            vertexesToUpdate = [vertexesToUpdate candidate];
            
            signalOut = UpdateVertexSignal(...
                            candidate, ...
                            candidateDependencies, ...
                            architecture, ...
                            weights, ...
                            signalOut);
        end
    end

return
end
