function ...
    [signalOut] = ...
UpdateVertexSignal(...
    candidate, ...
    dependenciesList, ...
    architecture, ...
    weights, ...
    signal)

    input = 0;
    signalOut = signal;
    dependenciesCount = size(dependenciesList, 2);
    
    for index = 1 : dependenciesCount
       dependency = dependenciesList(index);
       input = input + ...
                  signal(dependency) * ...
                  weights(dependency, candidate);
    end
    
    fcn = architecture.functions(candidate);
    signalOut(1, candidate) = fcn(input);
    
return
end
