function ...
    [ result ] = ...
InsertConnectionChain(...
    connections, ...
    fromIndex, ...
    toIndex, ...
    distance);
%SPLITTING a connection 
%

result = connections;

if (distance <= 0)
    error('[!!! ERROR !!!] : Cycles or loopbacks detected in the graph.');
elseif (distance == 1)
    return %%result
end


    lastAddedVertexIndex = fromIndex;
    splitOperationsCount = distance - 1;
    for index = 1 : splitOperationsCount
       [result, ...
        lastAddedVertexIndex] = SplitConnection(...
                                    result, ...
                                    lastAddedVertexIndex, ...
                                    toIndex); 
    end

return %%result
end
