function [updatedLocalOptimizer] = OnFirstCandidateMatch(localOptimizer)
%
%
%%%%%%%%%%%%%%%%
    config = NetworkOptimizerConfiguration();
    growthFactor = config.loaclOptimizeStepGrowthFactor;
Trace('First candidate matches. Changing direction.', 3);

    updatedLocalOptimizer = localOptimizer;

    if ( updatedLocalOptimizer.vvec )
        updatedLocalOptimizer.candidate.weights = ...
            updatedLocalOptimizer.candidate.weights + ...
            updatedLocalOptimizer.candidateDelta;
    
        updatedLocalOptimizer.statisticGradient = ...
            updatedLocalOptimizer.statisticGradient + ...
            updatedLocalOptimizer.candidateDelta;
            
        updatedLocalOptimizer.candidateDelta = ...
            updatedLocalOptimizer.candidateDelta * ...
            growthFactor;

        updatedLocalOptimizer.vr = ...
            updatedLocalOptimizer.vr * ...
            growthFactor;
    else
        [row, col] = ParamIndexToMatrixCoordinates(...
                        updatedLocalOptimizer, ...
                        updatedLocalOptimizer.vi);
        
        updatedLocalOptimizer.candidate.weights(row, col) = ...
            updatedLocalOptimizer.candidate.weights(row, col) + ...
            updatedLocalOptimizer.vr;
        
            
        updatedLocalOptimizer.statisticGradient(row, col) = ...
            updatedLocalOptimizer.statisticGradient(row, col) + ...
            updatedLocalOptimizer.vr;
        
        updatedLocalOptimizer.vr = ...
            updatedLocalOptimizer.vr * ...
            growthFactor;
    end

    updatedLocalOptimizer.candidate.error = ...
        CheckedSimulateNetwork( ...
            updatedLocalOptimizer, ...
            updatedLocalOptimizer.candidate.weights ...
        );
    
return
end


